### ISSUE TITLE
Shelf/Campus Dataset

### ISSUE THREAD

**Issue by wngTn** [sail-sg/mvp#13]
Does someone have another repository where I can download the shelf and campus dataset? As the current one is not available anymore.

Thanks

**Comment by JACKYLUO1991** [comment]
@wngTn Have you found it, please? I am having the same doubts.

**Comment by JACKYLUO1991** [comment]
@wngTn You can visit https://github.com/longcw/crossview_3d_pose_tracking address to find what you are looking for.
