### ISSUE TITLE
Does the mvp support batch_size>1?

### ISSUE THREAD

**Issue by guoguangchao** [sail-sg/mvp#2]
Line 130 of the projatt.py:
n_views, Len_q, c = query.shape
does the n_views means batch_size*num_cam?

**Comment by twangnh** [comment]
batch size 2 is not supported, you may modify it by yourself.

**Comment by guoguangchao** [comment]
> 

thanks for your ansower

**Comment by Dragon2938734** [comment]
> > 
> 
> thanks for your ansower

excuseme, have you modify it to surpport batch_size>1?

**Comment by twangnh** [comment]
you may try the reimplementation: https://github.com/openxrlab/xrmocap
