### ISSUE TITLE
Questions about batch size larger than 1

### ISSUE THREAD

**Issue by wangjiongw** [sail-sg/mvp#20]
When I run the validation code with given pretrained checkpoint on Panoptic dataset, I found that there is something wrong with batch size larger than 1.
For example, 
When batch size=1, the precision can be reproduced.
![image](https://user-images.githubusercontent.com/29309804/177721828-09750464-a925-4b64-b31a-73ef8850b44f.png)

When batch size=2, it seems that the model fails to predict correctly.
![image](https://user-images.githubusercontent.com/29309804/177722042-6bda32a8-a064-444c-90ab-401428b60c4a.png)

Does anyone get the similar problem? Or can you please give some advice about the reason of this problem? thx!

**Comment by liqikai9** [comment]
I got the same problem as well when I reimplement the algorithm. The training speed is really slow and the performance is really bad.

Does anyone have a solution?

**Comment by wangjiongw** [comment]
> 

In this repo, I didn't find an available solution. But there is an re-implementation of MvP in Mocap (https://github.com/openxrlab/xrmocap), batch size larger than 1 is okay in that repo.

**Comment by twangnh** [comment]
please refer to https://github.com/openxrlab/xrmocap for improved implementation
